asked/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
]

questions/urls.py
from django.urls import path
from . import views

app_name = "questions"  # 같은 index라는 name을 가지고 있는 여러개의 앱이 있을 수 있으니까
# 이 앱의 이름으로 한번 더 그룹해서 겹쳐도 구분 가능하게 한다
urlpatterns = [
    # Read
    path('', views.index, name="index"),  # '' 를 보여주는 페이지이름을 index라고 부른다.
    path('<int:id>/', views.detail, name="detail"),

    path('create/', views.create, name="create"),

    path('<int:question_id>/answers/',
         views.answer_create, name="answer_create"),

    path('<int:question_id>/answers/<int:answer_id>/delete/',
         views.answer_delete, name="answer_delete"),
]

questions/models.py
from django.db import models

# Create your models here.

# 모델을 바꾸면 migrations


class Question(models.Model):
    content = models.TextField()


class Answer(models.Model):
    content = models.CharField(max_length=100)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

questions/views.py
from django.shortcuts import render, redirect
from .models import Question, Answer
# Create your views here.


def index(request):
    questions = Question.objects.all()  # 데이터 베이스에 있는 전체 정보를 불러옴
    context = {
        'questions': questions
    }
    return render(request, 'index.html', context)  # 그 정보를 딕셔너리에 담아서 인덱스에 넘겨줌


def detail(request, id):
    question = Question.objects.get(id=id)
    context = {
        'question': question,
    }
    return render(request, 'detail.html', context)


def create(request):
    if request.method == "POST":
        content = request.POST.get('content')
        Question.objects.create(content=content)

        return redirect('questions:index')  # 인덱스로 다시 보내준다.
    else:
        return render(request, 'form.html')


def answer_create(request, question_id):
    if request.method == "POST":
        content = request.POST.get('content')
        question = Question.objects.get(id=question_id)

        Answer.objects.create(content=content, question=question)

        return redirect('questions:detail', question_id)
    else:
        pass


def answer_delete(request, question_id, answer_id):
    answer = Answer.objects.get(id=answer_id)
    answer.delete()

    return redirect('questions:detail', question_id)

questions/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Asked</title>
  <!-- 부트스트랩 사용하기 위해서 적어준다. -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              <li><a href="{% url 'questions:create'%}" class="text-white">질문 추가하기</a></li>
              <li><a href="#" class="text-white">Like on Facebook</a></li>
              <li><a href="#" class="text-white">Email me</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
          <strong>Asked</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  {% block body %}
  {% endblock %}
  <!--부트스트랩 사용하기 위해서 적어준다. -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

questions/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="jumbotron">
    <p class="lead">{{question.content}}</p>
    <hr class="my-4">
    <form action="{% url 'questions:answer_create' question.id %}" method="post">
      {% csrf_token %}
      <input class="form-control" type="text" name="content">
      <input class="btn btn-primary" type="submit">
    </form>

    {% if question.answer_set.all %}
      {% for answer in question.answer_set.all %}
        <div class="alert alert-primary" role="alert">
          {{answer.content}}
          <a href="{% url 'questions:answer_delete' question.id answer.id %}" class="btn btn-danger">삭제</a>
        </div>
      {% endfor %}
    {% else %}
      <div class="alert alert-primary" role="alert">
        댓글이 없습니다.
      </div>
    {% endif%}
  </div>
</div>
{% endblock%}

questions/templates/form.html
{% extends 'base.html' %}
{% block body %}
  <div class="container w-50 my-3"> <!-- container 는 좌우 마진을 자동으로 맞춰줌-->
    <form action="" method="POST">
      {% csrf_token %} <!-- 내가 발행한거라는걸 알리기 위해 적어줘야한다. -->
      <textarea class="form-control" name="content" id="" rows="5" placeholder="질문을 남겨주세요"></textarea> <!-- placeholder는 클릭하면 사라짐 -->
      <input class="btn btn-danger" type="submit">
    </form>
  </div>
{% endblock %}

questions/templates/index.html
{% extends 'base.html' %}
{% block body %}
  <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">What is best question?</h1>
          <p class="lead text-muted">Something point is closed your relative.</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
          </p>
        </div>
      </section>
    
      <div class="album py-5 bg-light">
        <div class="container">
    
          <div class="row">
            {% for question in questions %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                <div class="card-body">
                  <p class="card-text">{{question.content}}<span class="badge badge-warning">{{question.answer_set.all.count}}</span></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'questions:detail' question.id %}" class="btn btn-sm btn-outline-secondary">상세보기</a>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            {% empty %}
              <h1 class="text-center">질문이 없습니다.ㅜㅜ</h1>
            {% endfor %}
          </div>
        </div>
      </div>
    
    </main>
{% endblock %}